#!/usr/bin/env python3
"""Render the per-paper anchor tables for the dataset-schema appendix.

Source data (read live from the repository, never hand-copied):
  outputs/v6/app_rebuild/eval_100.jsonl   -> the frozen 100-paper eval split
  outputs/v6/app_rebuild/dev_split.jsonl  -> the disjoint 14-paper dev split

Writes:
  paper_latex/tables/eval100.tex   (longtable tab:eval100 + table tab:dev14)

Also prints the tier counts, the per-tier band counts, the bar-kind counts, and
the schema invariants the appendix asserts, so the prose can be checked against
the data.

Usage: python3 paper_latex/tables/gen_eval100.py
Override the lockfile location with RECLAIM_LOCKFILE_DIR.
"""

from __future__ import annotations

import json
import os
from collections import Counter
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
LOCKFILE_DIR = Path(os.environ.get("RECLAIM_LOCKFILE_DIR", REPO / "outputs" / "v6" / "app_rebuild"))
EVAL = LOCKFILE_DIR / "eval_100.jsonl"
DEV = LOCKFILE_DIR / "dev_split.jsonl"
OUT = REPO / "paper_latex" / "tables" / "eval100.tex"

# The lockfile stores the artifact tiers under their construction-time names.
TIER_NAME = {"Easy": "Run", "Medium": "Retrain", "Hard": "Reimplement"}
TIER_ORDER = ["Easy", "Medium", "Hard"]
BAND_ORDER = ["0-8", "8-32", "32-96", "96-192"]
METRIC_CHARS = 28
VALUE_CHARS = 28

SPECIAL = {
    "&": r"\&", "%": r"\%", "$": r"\$", "#": r"\#", "_": r"\_",
    "{": r"\{", "}": r"\}", "~": r"\textasciitilde{}", "^": r"\textasciicircum{}",
    "\\": r"\textbackslash{}", "<": r"\textless{}", ">": r"\textgreater{}",
    "|": r"\textbar{}",
    "×": r"$\times$", "±": r"$\pm$", "°": r"$^\circ$",
    "²": r"$^2$", "³": r"$^3$", "₂": r"$_2$",
    "é": r"\'e", "Å": r"\AA{}",
    "λ": r"$\lambda$", "χ": r"$\chi$", "–": "--", "—": "---",
    "→": r"$\rightarrow$", "≥": r"$\geq$", "≤": r"$\leq$",
    "≈": r"$\approx$", "’": "'", "“": "``", "”": "''",
}


def tex(text: str) -> str:
    out = []
    for ch in text:
        if ch in SPECIAL:
            out.append(SPECIAL[ch])
        elif ord(ch) > 127:
            out.append("?")
        else:
            out.append(ch)
    return "".join(out)


def clip(text: str, limit: int) -> str:
    text = " ".join(text.split())
    if len(text) <= limit:
        return text
    head = text[:limit].rsplit(" ", 1)[0].rstrip(" ,;:.")
    if not head:
        head = text[:limit]
    return head + "..."


def load(path: Path) -> list[dict]:
    return [json.loads(line) for line in path.read_text(encoding="utf-8").splitlines() if line.strip()]


def sort_key(row: dict):
    return (
        TIER_ORDER.index(row["tier"]),
        BAND_ORDER.index(row["h100_band"]),
        row["custom_id"],
    )


def cells(row: dict) -> list[str]:
    target = row["match_target"]
    bar = target.get("match_bar_kind", "unset").replace("_", " ")
    hours = row["audited_h100_hours"]
    shown = f"{hours:.2f}" if hours == 0 or hours >= 0.005 else "$<$0.01"
    # The preamble has no array package, so the ragged setting goes in the cell.
    # Rows end with \tabularnewline, which \raggedright leaves alone.
    ragged = "\\raggedright "
    return [
        tex(row["custom_id"]),
        TIER_NAME[row["tier"]],
        tex(row["h100_band"].replace("-", "--")),
        shown,
        ragged + tex(clip(target["metric"], METRIC_CHARS)),
        ragged + tex(bar),
        ragged + tex(clip(target["value"], VALUE_CHARS)),
    ]


# The preamble loads longtable but not array, so no >{...} column modifiers.
COLSPEC = (
    "@{}l@{\\hspace{5pt}}l@{\\hspace{5pt}}c@{\\hspace{5pt}}r@{\\hspace{5pt}}"
    "p{2.35cm}@{\\hspace{5pt}}p{1.4cm}@{\\hspace{5pt}}p{2.75cm}@{}"
)
HEAD = "arXiv & Tier & Band & H100-h & Metric & Bar & Target value \\\\"

EVAL_CAPTION = (
    "The 100 evaluation papers, one row each, sorted by tier, then compute band, "
    "then arXiv ID. Tier is the dataset's artifact tier under the "
    "Run/Retrain/Reimplement names. Band is the compute band in H100-hours and "
    "H100-h is the audited estimate for that paper's match target. Metric, Bar, "
    "and Target value are the pinned match target. Metric names and target "
    f"values longer than {METRIC_CHARS} characters are cut and closed with an "
    "ellipsis. One row has no bar kind and is written unset."
)
DEV_CAPTION = (
    "The 14 development papers, in the same columns and the same sort order. "
    "This split is disjoint from the evaluation set and is used for harness "
    f"development only. Metric names and target values longer than {METRIC_CHARS} "
    "characters are cut and closed with an ellipsis."
)


def longtable(rows: list[dict]) -> str:
    lines = [
        "% Generated by paper_latex/tables/gen_eval100.py. Do not edit by hand.",
        "% src: outputs/v6/app_rebuild/eval_100.jsonl",
        "{\\footnotesize",
        f"\\begin{{longtable}}{{{COLSPEC}}}",
        f"\\caption{{{EVAL_CAPTION}}}",
        "\\label{tab:eval100} \\\\",
        "\\toprule",
        HEAD,
        "\\midrule",
        "\\endfirsthead",
        "\\multicolumn{7}{@{}l}{\\footnotesize\\itshape Table~\\ref{tab:eval100}, continued.} \\\\",
        "\\toprule",
        HEAD,
        "\\midrule",
        "\\endhead",
        "\\midrule",
        "\\multicolumn{7}{@{}r}{\\footnotesize\\itshape continued on the next page} \\\\",
        "\\endfoot",
        "\\bottomrule",
        "\\endlastfoot",
    ]
    for row in sorted(rows, key=sort_key):
        lines.append(" & ".join(cells(row)) + " \\tabularnewline")
    lines += ["\\end{longtable}", "}", ""]
    return "\n".join(lines)


def devtable(rows: list[dict]) -> str:
    lines = [
        "% src: outputs/v6/app_rebuild/dev_split.jsonl",
        "{\\footnotesize",
        f"\\begin{{longtable}}{{{COLSPEC}}}",
        f"\\caption{{{DEV_CAPTION}}}",
        "\\label{tab:dev14} \\\\",
        "\\toprule",
        HEAD,
        "\\midrule",
        "\\endfirsthead",
        "\\multicolumn{7}{@{}l}{\\footnotesize\\itshape Table~\\ref{tab:dev14}, continued.} \\\\",
        "\\toprule",
        HEAD,
        "\\midrule",
        "\\endhead",
        "\\bottomrule",
        "\\endlastfoot",
    ]
    for row in sorted(rows, key=sort_key):
        lines.append(" & ".join(cells(row)) + " \\tabularnewline")
    lines += ["\\end{longtable}", "}", ""]
    return "\n".join(lines)


def summary(name: str, rows: list[dict]) -> None:
    print(f"--- {name} (n={len(rows)}) ---")
    tiers = Counter(row["tier"] for row in rows)
    print("tiers:", ", ".join(f"{TIER_NAME[t]} {tiers[t]}" for t in TIER_ORDER))
    for tier in TIER_ORDER:
        sub = [r for r in rows if r["tier"] == tier]
        bands = Counter(r["h100_band"] for r in sub)
        hours = sum(r["audited_h100_hours"] for r in sub)
        band_str = "/".join(str(bands.get(b, 0)) for b in BAND_ORDER[:3])
        print(f"  {TIER_NAME[tier]:<12} bands 0-8/8-32/32-96 = {band_str}   audited H100-h {hours:.2f}")
    print(f"  total audited H100-h {sum(r['audited_h100_hours'] for r in rows):.2f}")
    bars = Counter(r["match_target"].get("match_bar_kind", "<absent>") for r in rows)
    print("bar kinds:", ", ".join(f"{k} {v}" for k, v in bars.most_common()))
    basis = Counter(r["h100_estimate"]["basis_kind"] for r in rows)
    print("estimate basis:", ", ".join(f"{k} {v}" for k, v in basis.most_common()))
    for field, expected in [
        ("paper_kind", "empirical"),
        ("verification_status", "verified"),
        ("web_verification", "available"),
        ("exit_reason", "natural"),
    ]:
        bad = [r["custom_id"] for r in rows if r[field] != expected]
        print(f"  all {field}=={expected}: {not bad}" + (f"  exceptions {bad}" if bad else ""))
    bad_band = [r["custom_id"] for r in rows if r["h100_band"] != r["selection_band"]]
    print(f"  h100_band==selection_band: {not bad_band}" + (f"  exceptions {bad_band}" if bad_band else ""))
    true_untooled = [
        (r["custom_id"], k)
        for r in rows
        for k, v in r["signals"].items()
        if v["value"] and v["verification"] != "tool_verified"
    ]
    print(f"  every true signal is tool_verified: {not true_untooled}"
          + (f"  exceptions {true_untooled}" if true_untooled else ""))
    na = Counter(k for r in rows for k, v in r["signals"].items() if v["verification"] == "not_applicable")
    print("  not_applicable signals:", dict(na) or "none")
    print("  score->tier:", dict(Counter(f"{r['score']}->{TIER_NAME[r['tier']]}" for r in rows)))
    nulls = Counter(
        k for r in rows for k in ("h100_recomputed_hours", "h100_arithmetic_mismatch") if r[k] is None
    )
    print("  null-valued fields:", dict(nulls) or "none")
    est_nulls = Counter(
        k for r in rows for k in ("gpu_count", "gpu_type", "wallclock_hours", "h100_equivalent_multiplier")
        if r["h100_estimate"][k] is None
    )
    print("  null h100_estimate fields:", dict(est_nulls) or "none")
    adjudicated = [r["custom_id"] for r in rows if r["h100_hours_adjudicated"]]
    moved = [r["custom_id"] for r in rows if r["audited_h100_hours"] != r["h100_estimate"]["hours"]]
    print(f"  adjudicated rows {len(adjudicated)}; audited hours differ from the estimate on"
          f" {len(moved)}; same rows: {set(adjudicated) == set(moved)}")
    long_metric = sum(1 for r in rows if len(r["match_target"]["metric"]) > METRIC_CHARS)
    long_value = sum(1 for r in rows if len(r["match_target"]["value"]) > VALUE_CHARS)
    print(f"  truncated cells: metric {long_metric}, target value {long_value}")


def main() -> int:
    ev, dv = load(EVAL), load(DEV)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(longtable(ev) + "\n" + devtable(dv), encoding="utf-8")
    print(f"wrote {OUT} ({OUT.stat().st_size} bytes)")
    summary("eval (test split)", ev)
    summary("dev (validation split)", dv)
    overlap = {r["custom_id"] for r in ev} & {r["custom_id"] for r in dv}
    print(f"--- splits disjoint: {not overlap} ---")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
